using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using FrotaVeiculoPim;
using Pim_ControleFrota;
using Pim_ControleFrota.Class_DAO;

namespace FrotaVeiculoPim.Views
{
    /// <summary>
    /// Interação lógica para UserControlCadVeiculo.xam
    /// </summary>
    public partial class UserControlCadVeiculo : UserControl
    {
        static int Id;
        public UserControlCadVeiculo()
        {
            InitializeComponent();
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            //Seguro seguro = new Seguro();
           // seguro.ShowDialog();
        }

        private void TextBox_TextChanged(object sender, TextChangedEventArgs e)
        {
            
        }

        private void BtnCadSeguro_Click(object sender, RoutedEventArgs e)
        {
            MainWindow mainWindow = new MainWindow();
            CadSeguro cadSeguro = new CadSeguro();
            mainWindow.Show();
            mainWindow.imgFundo.Visibility = Visibility.Collapsed;
            mainWindow.ButtonCloseMenu.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));
            mainWindow.GridPrincipal.Children.Add(cadSeguro);
        }

        private void BtnListaVeiculo_Click(object sender, RoutedEventArgs e)
        {
            ClassVeiculoDAO veiculoDAO = new ClassVeiculoDAO();
            cadVeiculo.Visibility = Visibility.Hidden;
            listaVeiculo.Visibility = Visibility.Visible;
            dgListar.ItemsSource = veiculoDAO.ListarVeiculo();
        }

        private void BtnVoltar_Click(object sender, RoutedEventArgs e)
        {
            listaVeiculo.Visibility = Visibility.Hidden;
            cadVeiculo.Visibility = Visibility.Visible;
        }

        private void Button_Click_1(object sender, RoutedEventArgs e)
        {
            ClassVeiculos veiculos = new ClassVeiculos();
            veiculos.Ano = Convert.ToInt32(txtAno.Text);
            veiculos.Cor = txtCor.Text;
            veiculos.Marca = txtMarca.Text;
            veiculos.Modelo = txtModelo.Text;
            veiculos.Nome = txtNomeVeiculo.Text;
            veiculos.Renavan = txtRenavan.Text;
            veiculos.Placa = txtPlaca.Text;
            ClassVeiculoDAO veiculoDAO = new ClassVeiculoDAO();
            veiculoDAO.Cadastrar(veiculos);
            MessageBox.Show("cadastrado");
        }

        private void DgListar_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dgListar.Columns[0].Visibility = Visibility.Collapsed;
            dgListar.Columns[1].Width = 200;
            dgListar.Columns[2].Width = 130;
            dgListar.Columns[3].Width = 250;
            dgListar.Columns[4].Width = 100;
            dgListar.Columns[5].Width = 130;
            dgListar.Columns[6].Width = 130;
            dgListar.Columns[7].Width = 110;

        }

        private void DgListar_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            listaVeiculo.Visibility = Visibility.Collapsed;
            cadVeiculo.Visibility = Visibility.Visible;
            btnVoltar.Visibility = Visibility.Collapsed;
              btnSalvar.Visibility = Visibility.Collapsed;
              btnAlterar.Visibility = Visibility.Visible;
            ClassVeiculos veiculos = new ClassVeiculos();
            veiculos = dgListar.SelectedItem as ClassVeiculos;
            txtNomeVeiculo.Text = veiculos.Nome;
            txtPlaca.Text = veiculos.Placa;
            txtRenavan.Text = veiculos.Renavan;
            txtAno.Text = veiculos.Ano.ToString();
            txtCor.Text = veiculos.Cor;
            txtMarca.Text = veiculos.Marca;
            txtModelo.Text = veiculos.Modelo;
            Id = veiculos.Codigo;
        }

        private void BtnAlterar_Click(object sender, RoutedEventArgs e)
        {
            ClassVeiculoDAO veiculoDAO = new ClassVeiculoDAO();
            ClassVeiculos veiculos = new ClassVeiculos();
            veiculos.Ano = Convert.ToInt32(txtAno.Text);
            veiculos.Cor = txtCor.Text;
            veiculos.Marca = txtMarca.Text;
            veiculos.Modelo = txtModelo.Text;
            veiculos.Nome = txtNomeVeiculo.Text;
            veiculos.Renavan = txtRenavan.Text;
            veiculos.Placa = txtPlaca.Text;
            veiculoDAO.Alterar(veiculos);
            MessageBox.Show("alterado");
        }
    }
}
